name: main_py3_12
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - catboost
  - rdkit
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - notebook
  - ipykernel
  - pip
